
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/head_first.ipynb
def add_number(a, b):
    "Basic Function to `Add` two number"
    return a+b

def add_number_three(a, b, c):
    "Basic Function to `Add` Three number"
    return a+b+c

def mult_numbers(a, b):
    "Basic Function to `Mul` two number"
    return a*b